lesta/lesta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('text_app.urls')),
]

lesta/text_app/urls.py
from django.urls import path, include
from rest_framework.routers import SimpleRouter
from django.conf import settings
from django.conf.urls.static import static
from .views_api import (
    FileUploadViewSet,
    FileListRetrieveViewSet,)
from .views import (
    index,
    upload_file,
    file_words,
)

app_name = 'text_app'

router = SimpleRouter()
router.register('upload', FileUploadViewSet, basename='upload')
router.register('files', FileListRetrieveViewSet, basename='files')

urlpatterns = [
    path('api/', include(router.urls)),
    path('', index, name='index'),
    path('upload/', upload_file, name='upload_file'),
    path('file/<int:file_id>', file_words, name='file_words'),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

lesta/text_app/models.py
from django.db import models


class File(models.Model):
    file = models.FileField(
        verbose_name='Файл',
        upload_to='files/',
    )
    name = models.TextField(
        verbose_name='Название документа',
    )
    upload_at = models.DateTimeField(
        verbose_name='Время загрузки',
        auto_now_add=True,
    )
    quantity = models.IntegerField(
        verbose_name='Количество слов',
        null=True,
        default=0,
    )
    processed = models.BooleanField(
        verbose_name='Статус загрузки',
        default=False,
    )

    class Meta:
        verbose_name = 'Файл'
        verbose_name_plural = 'Файлы'


class Words(models.Model):
    file = models.ForeignKey(
        File,
        on_delete=models.CASCADE,
        related_name='words',
        verbose_name='Файл',
    )
    words_list = models.TextField(
        verbose_name='50 наиболее частых слов',
    )

    class Meta:
        verbose_name = 'Слова'
        verbose_name_plural = 'Слова'

lesta/text_app/forms.py
from django import forms
from .models import File


class FileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ('file', )

lesta/text_app/views.py
from .models import File
from django.shortcuts import render, redirect
from .forms import FileForm
import requests
from .func import make_paginator


def index(request):
    template = 'index.html'
    files_list = File.objects.all().order_by('-upload_at')
    page_obj = make_paginator(request, files_list)
    context = {
        'files': page_obj,
    }
    return render(request, template, context)


def upload_file(request):
    template = 'upload.html'
    form = FileForm(request.POST or None, files=request.FILES or None)
    if request.method == 'POST':
        file = request.FILES['file']
        r = requests.post(
            'http://127.0.0.1:8000/api/upload/',
            files=[('file', file)],
        )
        if r.status_code == 201:
            return redirect('text_app:index')
        else:
            pass
            return render(request, template, {'form': form,
                                              'warning': True})
    else:
        return render(request, template, {'form': form})


def file_words(request, file_id):
    template = 'file_words.html'
    file_words_list_response = requests.get(
        'http://127.0.0.1:8000/api/files/'+str(file_id),
    )
    file_words_list = file_words_list_response.json()
    context = {
        'file': file_words_list,
    }
    return render(request, template, context)

lesta/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Подсчет количества и частоты слов">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" href="{% static 'src/favicon.png' %}" type="image">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main_page.css' %}">
</head>
<body class="wrapper">

  <header class="">
    <div class="container head-container">
      <p style='margin-left: 138px'></p>
      <a href="http://127.0.0.1:8000/"><img src="{% static 'src/favicon.png' %}" style="width:100px; height:100px;"></a>
      {% if form %}
        <p style='margin-left: 138px'></p>
      {% else %}
        <a class="btn btn-light" href="http://127.0.0.1:8000/upload/" role="button">Загрузить файл</a>
      {% endif %}
    </div>
  </header>

  <main class="container">
    <h2 class="table-style" style="margin: 50px;">
      <b></b>
      <span class="table-title">{% block heading %}{% endblock %}</span>
      <b></b>
    </h2>
    {% block content %}
    {% endblock %}
  </main>

</body>
</html>

lesta/templates/file_words.html
{% extends 'base.html' %}
{% block title %}
  Частотный анализ слов
{% endblock %}
{% block heading %}
  Частотный анализ слов
{% endblock %}
{% block content %}
  <table>
    <tbody>
      <tr>
        <td width="750">
          <h5>{{ file.name }}</h5>
        </td>
        <td width="200">
          <h5>Количесво слов:</h5>
        </td>
        <td width="100">
          <h5>{{ file.quantity }}</h5>
        </td>
      </tr>
    </tbody>
  </table>

  <table style="margin-bottom: 100px">
    <tbody>
      <tr>
        <td width="450">
          <h5>Слово</h5>
        </td>
        <td width="300">
          <h5>Количесво встречь</h5>
        </td>
        <td width="300">
          <h5>Частота слова в %</h5>
        </td>
      </tr>
      {% for word in file.words.0.words_list %}
        <tr>
          <td>{{ word.0 }}</td>
          <td>{{ word.1 }}</td>
          <td>{{ word.2 }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

lesta/templates/index.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}
  Lesta Games
{% endblock %}
{% block heading %}
  Ранее загруженные файлы
{% endblock %}
{% block content %}
  {% if files %}
    <table style="margin-bottom: 100px">
      <tbody>
        <tr>
          <td width="500">
            <h5>Файл</h5>
          </td>
          <td width="250">
            <h5>Дата добаления</h5>
          </td>
          <td width="200">
            <h5>Количесво слов</h5>
          </td>
          <td width="100">
            <h5>Обработано</h5>
          </td>
        </tr>
        {% for file in files %}
            <tr>
              <td>
                {% if file.processed %}
                  <a href="{% url 'text_app:file_words' file.id %}">
                    {{ file.name }}
                  </a>
                {% else %}
                  {{ file.name }}
                {% endif %}
              </td>
              <td>{{ file.upload_at }}</td>
              <td>{{ file.quantity }}</td>
              <td>{{ file.processed }}</td>
            </tr>
        {% endfor %}
      </tbody>
    </table>
    <div>
      {% include 'paginator.html' %}
    </div>
  {% else %}
    <div class="pagination">
      <a href="http://127.0.0.1:8000/upload/">
        <h3 class="table-style">
          Загрузите первый файл!
        </h3>
      </a>
    </div>
  {% endif %}
{% endblock %}

lesta/templates/paginator.html
{% if files.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if files.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ files.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in files.paginator.page_range %}
        {% if files.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if files.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ files.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ files.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %} 

lesta/templates/upload.html
{% extends 'base.html' %}
{% block title %}
  Загрузка файла
{% endblock %}
{% block heading %}
  Загрузите файл
{% endblock %}
{% block content %}
  <form method="post" action="{% url 'text_app:upload_file' %}" enctype="multipart/form-data">
  {% csrf_token %}
    <h3 style="margin-bottom: 50px">Загрузите файл в формате .txt</h3>
  {{ form.as_p }}
  {% if warning %}
    <div>
      <p>Упс! Что-то пошло не так.</p>
      <p>Попробуйте загрузить другой файл.</p>
    </div>
  {% endif %}
  <div style="margin: 50px"class="d-flex justify-content-center">
    <button type="submit" class="btn btn-light">
      Загрузить
    </button>
  </div>
{% endblock %}